### ISSUE TITLE
Typo in index.js line 30 branch sprint-2-base

### ISSUE THREAD

**Issue by jgwhitehead** [academyjs/samplecode#1]
var instructionSetResource = require('./libs/rest/InstructionSetResource');
should be
var instructionSetResource = require('./libs/rest/instructionSetResource');

I would create a pull request but I don't have rights

**Comment by academyjs** [comment]
Good spot. Works fine on Windows as it is not case sensitive. I'll update it

**Comment by academyjs** [comment]
Now fixed
