### ISSUE TITLE
Sprint 2 solution not uploaded

### ISSUE THREAD

**Issue by scottrowley** [academyjs/samplecode#3]
It looks as though sprint 2 doesn't have a solution uploaded (sprint2-base is up to date with sprint2-solution).

**Comment by academyjs** [comment]
Think that is just because I worked backwards when creating the branches. Just checked and sprint 2 base and the solution are different

**Comment by academyjs** [comment]
Have a look in InstructionSetResource. In the base branch there is missing code however in the solution it is complete

**Comment by scottrowley** [comment]
I see it now :) I'll close this then.
